version: '3.2'
services: 
    etcd-server:
      networks:
        - app-tier
      ports:
        - "2379:2379"
        - "2380:2380"
      environment:
        - ALLOW_NONE_AUTHENTICATION="yes"
        - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
        - ETCD_ADVERTISE_CLIENT_URLS=http://etcd-server:2379
      image: gcr.io/etcd-development/etcd:v3.3.10
      volumes:
        - type: bind
          source: /tmp/etcd-data.tmp
          target: /etcd-data
    etcd-client:
      networks:
        - app-tier
      build: etcdClient
      depends_on: 
        - etcd-server
      environment:
        - ETCDCTL_API=3
networks:
    app-tier:
volumes:
    etcd_data:
