version: '3.2'
services: 
    etcd-server:
      networks:
        - app-tier
      ports:
        - "2379:2379"
        - "2380:2380"
      environment:
        - ALLOW_NONE_AUTHENTICATION="yes"
        - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
        - ETCD_ADVERTISE_CLIENT_URLS=http://etcd-server:2379
      image: gcr.io/etcd-development/etcd:v3.3.10
      volumes:
        - type: bind
          source: /tmp/etcd-data.tmp
          target: /etcd-data
    confd:
      networks:
        - app-tier
      build: confd
      depends_on: 
        - etcd-curl
    etcd-curl:
      networks:
        - app-tier
      build: etcdCurl
      depends_on: 
        - etcd-server
      environment:
        - ALLOW_NONE_AUTHENTICATION='yes'
    py-app:
      networks:
        - app-tier
      build: pyApp
#      depends_on: nginx
networks:
    app-tier:
volumes:
 etcd-data:
