version: '3.2'
services: 
    etcd-server:
      networks:
        - app-tier
      ports:
        - "2379:2379"
        - "2380:2380"
      environment:
        - ALLOW_NONE_AUTHENTICATION="yes"
#        - ETCD_NAME=s1
#        - ETCD_DATA_DIR=/etcd-data
        - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
#        - ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379
        - ETCD_ADVERTISE_CLIENT_URLS=http://etcd-server:2379
#        - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
#        - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://0.0.0.0:2380
#        - ETCD_INITIAL_CLUSTER=s1=http://0.0.0.0:2380
#        - ETCD_INITIAL_CLUSTER_TOKEN=tkn
#        - ETCD_INITIAL_CLUSTER_STATE=new
      image: gcr.io/etcd-development/etcd:v3.3.10
      volumes:
        - type: bind
          source: /tmp/etcd-data.tmp
          target: /etcd-data
#    etcd-client:
#      networks:
#        - app-tier
#      environment:
#        - ALLOW_NONE_AUTHENTICATION="yes"
#      build: etcdClient
#      volumes:
#        - type: bind
#          source: /tmp/etcd-data.tmp
#          target: /etcd-data
#    confd:
#      build: confd
#      networks:
#        - app-tier
networks:
    app-tier:
volumes:
    etcd-data:
