[template]
prefix = "/myapp"
src = "nginx.tmpl"
dest = "/tmp/myapp.conf"
owner = "nginx"
mode = "0644"
keys = [
  "/subdomain",
  "/upstream",
]
#check_cmd = "nginx -t -c {{.src}}"
#reload_cmd = "rc-service nginx reload"
check_cmd = "nginx -t -c {{.src}}"
reload_cmd = "nginx -s reload"
