#Adapted from https://github.com/kelseyhightower/confd/blob/master/docs/installation.md
FROM appropriate/curl:latest
RUN mkdir -p insert
COPY insertkeys.sh insert/entrypoint.sh
RUN chmod +x insert/entrypoint.sh

